development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iokooqkhhwcmjf:183b29ac9fffd32f0e95ecd716f82dfee060af54d13c27a16684119f7b8e6dd0@ec2-54-225-118-55.compute-1.amazonaws.com:5432/d10gtvegp04tpg